### ISSUE TITLE
COVID Risk assessment data

### ISSUE THREAD

**Issue by sirgallo** [sirgallo/Restaurateur.io#1]

**Comment by sirgallo** [comment]
Use AWS Data Exchange, ExpressJS API for accessing.

**Comment by pelletiera1** [comment]
Trying to figure out the most efficient way to collect coordinates / data about different restaurants across America. Impossible to enter locations one by one, so I am looking for databases that are accessible for free.

**Comment by sirgallo** [comment]
Was successfully able to utilize ExpressJS and the AWS SDK to enable connections with Amazon Athena, where the Covid data was housed in S3 (from AWS data exchange).
